[theme]
primaryColor = "#567d46"  # Forest Green
backgroundColor = "#eaf4e6"  # Soft Sage Green
secondaryBackgroundColor = "#cbe0b8"  # Light Olive Green (for Sidebar)
textColor = "#2c3e50"  # Deep Navy Blue
font = "sans serif"